version: "3.4"

services:

  client:
    build:
      context: ./client
      args:
          - PYTHON3_VERSION
          - LIBINDY_REPO_COMPONENT
          - LIBINDY_VERSION
          - LIBSOVTOKEN_INSTALL
          - LIBSOVTOKEN_VERSION
          - u_id
    image: ${IMAGE_REPOSITORY}:client

  node:
    build:
      context: ./node
      args:
          - INDY_NODE_REPO_COMPONENT
          - LIBINDY_CRYPTO_VERSION
          - PYTHON3_LIBINDY_CRYPTO_VERSION
          - INDY_PLENUM_VERSION
          - INDY_NODE_VERSION
          - TOKEN_PLUGINS_INSTALL
          - SOVTOKEN_VERSION
          - SOVTOKENFEES_VERSION
    image: ${IMAGE_REPOSITORY}:node
